### ISSUE TITLE
[SPIKE] Cosmos db scaling and performance investigation

### ISSUE THREAD

**Issue by johevemi** [Energinet-DataHub/geh-aggregations#227]
**Description**
Make sure cosmos db performs well enough as data source for databricks, when running aggregations.

We want to ensure that we have sufficient understanding and confidence in using cosmos DB as master data storage

**AC**
1. How many RU does an aggregation over one day consume?
2. Ensure autoscaling is working
3. understand auto scaling mechanism  
4. understand performance relationship between databricks and cosmos db

**Comment by kristianschneider** [comment]
Findings from investigation:

One has to create a "Log Analytics workspace" in the resource group and than set that up in the diagnostics setttings for the Cosmos instance. This allows us to get metrics on consumption. 
We can pull out that data with the following query:

`AzureMetrics
| where MetricName == "TotalRequestUnits"
| extend RUsPerMinute = Total / 60
| extend RUsPerSecond = RUsPerMinute / 60
| extend RequestsPerMinute = Count / 60
| project-rename MaxRURequest = Maximum
| project TimeGenerated, RUsPerMinute, RequestsPerMinute, MaxRURequest, RUsPerSecond
| sort by TimeGenerated desc`

A run on current data, with beginning-date-time=2013-01-01T00:00:00Z","--end-date-time=2013-01-01T01:00:00Z", gave the following result:

|TimeGenerated [Local Time]|RUsPerMinute       |RequestsPerMinute  |MaxRURequest    |RUsPerSecond        |
|--------------------------|-------------------|-------------------|----------------|--------------------|
|8/18/2021, 1:41:00.000 PM |0.43333333333333335|0.43333333333333335|1               |0.007222222222222223|
|8/18/2021, 1:40:00.000 PM |2.75073420595145   |1.2833333333333334 |17              |0.04584557009919084 |
|8/18/2021, 1:28:00.000 PM |0.35               |0.35               |1               |0.005833333333333333|
|8/18/2021, 1:27:00.000 PM |109.35890187462566 |30.833333333333332 |6.17004267744834|1.8226483645770943  |
|8/18/2021, 1:26:00.000 PM |213.99733937228666 |60.28333333333333  |6.17004267744834|3.5666223228714444  |
|8/18/2021, 1:25:00.000 PM |70.25643714552449  |20.5               |6.17004267744834|1.1709406190920748  |


This would have to be repeated on a larger dataset to validate expected real consumption.

In regards of autoscaling the following has been observed:

_"With autoscale, the system scales the throughput (RU/s) T up or down within the 0.1 * Tmax and Tmax range, based on incoming traffic. Because the scaling is automatic and instantaneous, at any point in time, you can consume up to the provisioned Tmax with no delay."_

More on DBR and Cosmos 
[https://tsmatz.wordpress.com/2019/07/19/azure-cosmosdb-spark-connector-partition-throughput/](https://tsmatz.wordpress.com/2019/07/19/azure-cosmosdb-spark-connector-partition-throughput/)

This guy could be usefull to get in contact with for validation of our approach:
[https://github.com/FabianMeiswinkel](https://github.com/FabianMeiswinkel)
