### ISSUE TITLE
[Enabler] Investigate refactoring effort for Coordinator

### ISSUE THREAD

**Issue by mknic** [Energinet-DataHub/geh-aggregations#353]
Outcome:
1) A list of issues on what and how to refactor to make the Coordinator fit the context it should handle. This issue is related to #331 and those two should be part of making the decision on how to proceed.

2) Review with team

3) Review with Software arch.

**Comment by mknic** [comment]
As is our Coordinator serves to many different topics eg. handle result messages from aggregation and wholesale, trigger different databricks jobs (data preparation, aggregation, wholesale). Below bulletform list is improvements we see need to be implemented as part of the refactoring exercise of the coordinator. These will later be transformed into separate issues:

1. GreenEnergyHub.Aggregation.Application shouldn't have a dependency to databricks client. 
2. We need to separate responsibilities. The CoordinatorTrigger and CoordinatorService are responsible for starting different databricks jobs, handle aggregation/wholesale results and update snapshot path
3. Introduce MediatR pattern
4. Spit Azure Function into separate classes and move shared logic to a project (we avoid all functions are deployed together)

**To be continued...**

**Comment by mknic** [comment]
@Sondergaard will go through the list of issues created and referenced as part of this enabler today.

**Comment by Sondergaard** [comment]
This looks like a good starting point.

When you do the refactoring, try to do the refactoring in small iterations. The goal should be to move the source code in a certain direction, but the application should be usable the whole time - we don't wish the refactoring to block all team members while it is happening.

When you do refactor individual parts, remember to check if the code is tested, so that you have confidence in the work you deliver.

**Comment by mknic** [comment]
@Sondergaard thanks for great feedback. 
Our strategy is to do the refactoring in small steps as we need this part in a working stage to be able to reach our goals for the PI.
