### ISSUE TITLE
Refator events_data_lake_listener to use foreachpartition

### ISSUE THREAD

**Issue by kristianschneider** [Energinet-DataHub/geh-aggregations#488]
To ensure that work is better distributed when handling events to masterdata we should implement: https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.foreachPartition.html

AC1: Approach is implemented.
AC2: Improvement is verified with load test

**Comment by mknic** [comment]
@ZavezX and I've decided to move this issue back to the sprint backlog as it's due to optimization of a working process. We need to have another session with Databricks as we have questions we need to clarify to avoid spending a lot of time on implementing another version of the event streaming that can't perform sufficiently.

We have implemented some test code to handle this issue in the below branch:

[lki/foreach-partition](https://github.com/Energinet-DataHub/geh-aggregations/tree/lki/foreach-partition)

@kristianschneider has done some work on this as well in the following branch:
https://github.com/Energinet-DataHub/geh-aggregations/tree/feature/488_foreachpartition
