### ISSUE TITLE
[Enabler] Aggregation domain is JWT protectet and can be deployed again to T and B environments 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/geh-aggregations#637]
Synopsis
----------------
We are required to authenticate a forwarded JWT token by the SA. To live up to the Energinet dictated security standard for DataHubV3 as of now.

Acceptance criteria
----------------
- [x] All Aggregations function endpoints must authenticate the JWT token in the incoming message.

Tech Notes
----------------
- [x] SnapshotReceiver
- [x] ResultReceiver
- [x] KickStartWholesaleJob
- [x] KickStartJob
- [x] KickStartDataPreparationJobAsync

**Comment by lasrinnil** [comment]
Test
------------------------

Prepare endpoint reply with 401 when called without token

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/b9662143-15a
9-48c6-9ffd-edb522c2356d)


AggregationJob endpoint reply with 401 when called without token

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/57acae02-e3c9-4c3b-ad2c-aee736ed5166)

Both endpoints reply with 200 when called with a valid JWT Token. Which should be 202.

I have not tested other endpoints, and since the implementation of JWT token validation is not function method-specific but rather is implemented as a middleware in the function app itself. I don't see the need at the moment.

**Comment by ZavezX** [comment]
@lasrinnil The endpoints are not supposed to return 202 as the endpoints are not replying back to an actor. The endpoints are only used internally in the system.

**Comment by ZavezX** [comment]
The `SnapshotReceiver` and the `ResultReceiver` is excluded from JWT token authentication as we use the endpoints from databricks jobs.
